name: news-abstract
channels:
  - conda-forge
dependencies:
  - python=3.10
  - flake8
  - pytest
  - beautifulsoup4
  - pip
  - pip:
      - requests==2.31.0
      - lxml==4.9.3
      - langdetect==1.0.9
      - transformers==4.36.2
      - torch==2.1.2
      - spacy==3.7.2
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - nltk==3.8.1
      - numpy==1.24.3
