name: Python Package using Conda

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # 提前适配 Node 24

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate: true
        activate-environment: news-abstract   # 激活我们在 yml 中定义的环境
        environment-file: environment.yml     # 根据此文件创建环境
        conda-remove-defaults: true           # 保持频道干净

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        export PYTHONPATH=./src
        pytest
